import type { Language } from "./content";

export const busesControlContent = {
  en: {
    title: "Buses and control",
    intro:
      "The processor, memory and input/output ports exchange information along a system bus. Its three bus groups have different jobs.",
    cpu: "CPU",
    memory: "Memory",
    ports: "I/O ports",
    systemBus: "System bus",
    addressBus: "Address bus",
    dataBus: "Data bus",
    controlBus: "Control bus",
    where: "Where?",
    value: "What value?",
    request: "What request?",
    addressDirection: "CPU → memory / ports",
    dataDirection: "CPU ↔ memory / ports",
    controlSignals: "READ · WRITE",
    addressMeaning: "Carries the location being accessed, from the CPU toward memory or a port.",
    dataMeaning: "Carries the value being transferred. Its direction depends on the transfer.",
    controlMeaning:
      "Carries control signals such as READ and WRITE. The control bus is bidirectional overall; each signal has its own direction.",
    cu:
      "The control unit (CU) coordinates a transfer by issuing the appropriate control signal.",
    modePrompt: "Choose a transfer to explore.",
    read: "Read",
    write: "Write",
    tryIt: "Try it",
    readQuestion: "What will arrive in the CPU when address 11 is read?",
    writeQuestion: "After this write, what will change?",
    readChoices: ["42 arrives; memory stays the same", "Memory at 11 becomes 7"],
    writeChoices: [
      "Memory contents at address 12 change",
      "Address 12 changes to 6",
    ],
    prediction: "Check prediction",
    correctPrediction: "That prediction is right. Now follow the computer's transfers.",
    incorrectPrediction: "Not quite. Follow the transfers and compare the final state with your prediction.",
    predictFirst: "Make a prediction before showing the transfers.",
    readMemory: "Memory[11] = 42",
    readReceiver: "Receiver = 7",
    finalReceiver: "Receiver = 42",
    writeMemory: "Memory[12] = 9",
    finalMemory: "Memory[12] = 6",
    writeValue: "CPU value = 6",
    readEvents: [
      "The CPU places address 11 on the address bus, identifying the location to read.",
      "The control unit (CU) issues READ on the control bus.",
      "Memory returns 42 on the data bus toward the CPU.",
      "The receiver changes from 7 to 42. Memory at address 11 still contains 42.",
    ],
    writeEvents: [
      "The CPU places address 12 on the address bus, identifying where to write.",
      "The control unit (CU) issues WRITE on the control bus.",
      "The CPU sends value 6 on the data bus toward memory.",
      "Memory at address 12 changes from 9 to 6. Its address and other locations stay the same.",
    ],
    nextEvent: "Show next transfer",
    completed: "All transfers shown",
    nextPrompt: "Each lane has one job. Which one answers each question?",
    checkQuestion: "Match each question to a bus.",
    showMatches: "Show matches",
    hideMatches: "Hide matches",
    checkAnswers: ["Address bus", "Data bus", "Control bus"],
    reset: "Start again",
    home: "All explorations",
    homeEyebrow: "YOUR FOURTH EXPLORATION",
    homeTitle: "Buses and control",
    homeIntro:
      "How do a location, a request and returned information travel between the processor, memory and ports?",
    explore: "Explore buses and control",
    eventLabel: "Computer event",
  },
  zh: {
    title: "总线与控制",
    intro:
      "处理器、内存和输入／输出端口通过系统总线交换信息。系统总线中的三类总线各有不同作用。",
    cpu: "CPU（处理器）",
    memory: "内存",
    ports: "输入／输出端口",
    systemBus: "系统总线",
    addressBus: "地址总线",
    dataBus: "数据总线",
    controlBus: "控制总线",
    where: "哪个位置？",
    value: "什么数值？",
    request: "什么请求？",
    addressDirection: "CPU → 内存／端口",
    dataDirection: "CPU ↔ 内存／端口",
    controlSignals: "READ（读）· WRITE（写）",
    addressMeaning: "把正在访问的位置传向内存或端口。",
    dataMeaning: "传送正在交换的数值；传输方向取决于操作。",
    controlMeaning:
      "传送 READ（读）和 WRITE（写）等控制信号。总体来看，控制总线是双向的；每个信号都有自己的方向。",
    cu: "控制单元（CU）通过发出相应的控制信号来协调传输。",
    modePrompt: "选择一种传输过程来观察。",
    read: "读取",
    write: "写入",
    tryIt: "试一试",
    readQuestion: "读取地址 11 时，什么数值会到达处理器？",
    writeQuestion: "这次写入之后，什么会改变？",
    readChoices: ["处理器收到 42；内存保持不变", "地址 11 的内容变成 7"],
    writeChoices: ["地址 12 的内存内容会改变", "地址 12 会变成 6"],
    prediction: "查看预测",
    correctPrediction: "预测正确。现在按顺序观察计算机的传输。",
    incorrectPrediction: "还不完全正确。观察传输过程，再把最终状态和你的预测比较。",
    predictFirst: "先做出预测，再显示传输过程。",
    readMemory: "内存[11] = 42",
    readReceiver: "接收位置 = 7",
    finalReceiver: "接收位置 = 42",
    writeMemory: "内存[12] = 9",
    finalMemory: "内存[12] = 6",
    writeValue: "CPU 数值 = 6",
    readEvents: [
      "CPU 将地址 11 放到地址总线上，指出要读取的位置。",
      "控制单元（CU）在控制总线上发出 READ（读）信号。",
      "内存通过数据总线把 42 传回处理器。",
      "接收位置由 7 变为 42。地址 11 中仍然存着 42。",
    ],
    writeEvents: [
      "CPU 将地址 12 放到地址总线上，指出要写入的位置。",
      "控制单元（CU）在控制总线上发出 WRITE（写）信号。",
      "CPU 通过数据总线把数值 6 传向内存。",
      "地址 12 的内容由 9 变为 6。地址和其他位置保持不变。",
    ],
    nextEvent: "显示下一步传输",
    completed: "传输过程已显示完毕",
    nextPrompt: "每条总线各有作用。下面的问题分别由哪条总线回答？",
    checkQuestion: "把问题和总线对应起来。",
    showMatches: "显示对应关系",
    hideMatches: "隐藏对应关系",
    checkAnswers: ["地址总线", "数据总线", "控制总线"],
    reset: "重新开始",
    home: "所有探索",
    homeEyebrow: "你的第四次探索",
    homeTitle: "总线与控制",
    homeIntro: "位置、请求和返回的信息，如何在处理器、内存和端口之间传递？",
    explore: "探索总线与控制",
    eventLabel: "计算机执行的传输步骤",
  },
} satisfies Record<Language, Record<string, string | string[]>>;

export type BusesLanguage = Language;
