import type { Language } from "./content";

type ReviewQuestion = { prompt: string; choices: string[]; answer: number; explanation: string };
type FetchRegistersCopy = Record<string, string | string[] | ReviewQuestion[]>;

export const fetchRegistersContent = {
  en: {
    title: "Four registers, four jobs",
    homeEyebrow: "YOUR SIXTH EXPLORATION",
    homeIntro: "Meet the registers involved in fetching an instruction, then follow its address and contents through the processor and buses.",
    explore: "Explore the fetch registers",
    intro: "A processor contains small storage locations called registers. Each register has a particular job.",
    processor: "Processor",
    memory: "Main memory",
    pc: "Program Counter (PC)",
    mar: "Memory Address Register (MAR)",
    mdr: "Memory Data Register (MDR)",
    cir: "Current Instruction Register (CIR)",
    pcRole: "Holds the address of the next instruction to be fetched.",
    marRole: "Holds the address of the memory location currently being accessed.",
    mdrRole: "Temporarily holds data or an instruction transferred between memory and the processor.",
    cirRole: "Holds the current instruction while it is decoded and executed.",
    notFilled: "Not filled yet",
    memoryAt: "Location 20",
    standIn: "A readable stand-in, not machine code, for the instruction stored here.",
    instruction: "Display “Hello”",
    predictionLabel: "Your prediction",
    question: "Which register currently holds the address of the next instruction?",
    choices: ["PC", "MAR", "MDR", "CIR"],
    correct: "Yes. PC holds the address of the next instruction to be fetched.",
    tryAgain: "That register has a different job. Read each role, then compare again.",
    eventLabel: "Computer event",
    initialEvent: "PC currently holds 20. The computer has not started this relay yet.",
    next: "Show next computer step",
    completed: "All steps shown",
    reset: "Start again",
    home: "All explorations",
    addressBus: "Address bus",
    dataBus: "Data bus",
    controlBus: "Control bus",
    idle: "Idle",
    read: "READ",
    event1: "The computer copies 20 from PC into MAR. PC stays 20. This copy happens inside the processor; it does not travel along a system bus.",
    event2: "MAR supplies address 20 to the address bus, toward memory. The control unit sends READ on the control bus: the address says where; READ requests what memory should do.",
    event3: "Memory location 20 sends its instruction contents over the data bus into MDR. The address in MAR and the contents in memory stay unchanged.",
    event4: "The computer copies the instruction from MDR into CIR inside the processor. MDR keeps its value; CIR now holds the current instruction for later decoding and execution.",
    internalTransfer: "A copy between registers happens inside the processor; it does not travel along a system bus.",
    caveat: "This is a readable teaching example, not literal machine code or an instruction from a particular processor design.",
    partialRelay: "This guided view stops when the instruction reaches CIR. The later steps that complete the fetch are introduced in a following lesson.",
    eventIndex: ["Initial state", "PC to MAR", "Address and READ", "Memory to MDR", "MDR to CIR"],
    reviewTitle: "Check what travelled",
    reviewQuestions: [
      { prompt: "Which bus carried the location 20 to memory?", choices: ["Address bus", "Data bus", "Control bus"], answer: 0, explanation: "The address bus carries the memory location." },
      { prompt: "Which bus carried the instruction from memory to MDR?", choices: ["Address bus", "Data bus", "Control bus"], answer: 1, explanation: "The data bus carries the instruction contents." },
      { prompt: "Which control signal requested the memory read?", choices: ["READ", "WRITE", "The address 20"], answer: 0, explanation: "READ is the request; address 20 identifies the location." },
    ],
  },
  zh: {
    title: "四个寄存器，各有分工",
    homeEyebrow: "你的第六次探索",
    homeIntro: "认识取指过程中用到的寄存器，再跟着地址和指令内容观察它们如何经过处理器与总线。",
    explore: "探索取指寄存器",
    intro: "处理器里有一些称为寄存器的小型存储位置。每个寄存器都有特定的用途。",
    processor: "处理器",
    memory: "主存储器",
    pc: "程序计数器 PC",
    mar: "存储器地址寄存器 MAR",
    mdr: "存储器数据寄存器 MDR",
    cir: "当前指令寄存器 CIR",
    pcRole: "保存下一条要取出的指令的地址。",
    marRole: "保存当前正在访问的存储器位置的地址。",
    mdrRole: "暂时保存处理器与存储器之间传送的数据或指令。",
    cirRole: "保存当前指令，供处理器解码和执行。",
    notFilled: "尚未填写",
    memoryAt: "位置 20",
    standIn: "这是对所存指令的可读替代表示，不是机器码。",
    instruction: "显示“Hello”",
    predictionLabel: "你的预测",
    question: "哪个寄存器当前保存着下一条指令的地址？",
    choices: ["PC", "MAR", "MDR", "CIR"],
    correct: "是的。PC 保存着下一条要取出的指令的地址。",
    tryAgain: "这个寄存器的用途不同。读一读各自的职责，再比较一次。",
    eventLabel: "计算机事件",
    initialEvent: "PC 当前保存着 20。计算机还没有开始这段传送过程。",
    next: "显示计算机下一步",
    completed: "所有步骤已显示",
    reset: "重新开始",
    home: "全部探索",
    addressBus: "地址总线",
    dataBus: "数据总线",
    controlBus: "控制总线",
    idle: "空闲",
    read: "READ（读取）",
    event1: "计算机把 20 从 PC 复制到 MAR。PC 仍然是 20。这次复制发生在处理器内部，不经过系统总线。",
    event2: "MAR 把地址 20 放到通往存储器的地址总线上。控制单元在控制总线上发出 READ（读取）信号：地址说明“在哪里”，READ 请求存储器“做什么”。",
    event3: "存储器位置 20 把其中的指令内容通过数据总线送入 MDR。MAR 中的地址和存储器中的内容都保持不变。",
    event4: "计算机在处理器内部把 MDR 中的指令复制到 CIR。MDR 保持原值；CIR 现在保存着稍后供处理器解码和执行的当前指令。",
    internalTransfer: "寄存器之间的复制发生在处理器内部，不经过系统总线。",
    caveat: "这是便于阅读的教学示例，不是实际机器码，也不是某种特定处理器设计中的指令。",
    partialRelay: "本次引导观察在指令到达 CIR 时结束。之后的课程会继续讲解完成取指所需的后续步骤。",
    eventIndex: ["初始状态", "PC 到 MAR", "地址与 READ", "存储器到 MDR", "MDR 到 CIR"],
    reviewTitle: "检查传送的内容",
    reviewQuestions: [
      { prompt: "地址 20 通过哪条总线送到存储器？", choices: ["地址总线", "数据总线", "控制总线"], answer: 0, explanation: "地址总线传送存储器位置。" },
      { prompt: "指令从存储器传到 MDR 时经过哪条总线？", choices: ["地址总线", "数据总线", "控制总线"], answer: 1, explanation: "数据总线传送指令内容。" },
      { prompt: "哪个控制信号请求存储器读取？", choices: ["READ（读取）", "WRITE（写入）", "地址 20"], answer: 0, explanation: "READ 是读取请求；地址 20 指明位置。" },
    ],
  },
} satisfies Record<Language, FetchRegistersCopy>;

export type FetchRegistersLanguage = Language;
