import type { Language } from "./content";

export const instructionCycleContent = {
  en: {
    title: "The instruction cycle",
    intro: "A processor handles a program's instructions one after another.",
    homeEyebrow: "YOUR FIFTH EXPLORATION",
    homeIntro: "What does a processor do with an instruction, and what happens when it is finished?",
    explore: "Explore the instruction cycle",
    instructionMeaning: "An instruction is a direction that tells the processor what to do.",
    exampleLabel: "Two example instructions",
    instructions: ["Display “Hello”", "Display “Goodbye”"],
    cycleLabel: "The repeating instruction cycle",
    cycleMeaning: "Together, these three stages are called the instruction cycle.",
    phases: ["Fetch", "Decode", "Execute"],
    phaseDescriptions: [
      "Get the next instruction from memory.",
      "Work out what the instruction means.",
      "Carry out the instruction.",
    ],
    loopLabel: "Then return to fetch the next instruction",
    tryLabel: "Try it",
    question: "After the processor carries out “Display Hello”, what happens next?",
    choices: ["Fetch the next instruction", "Repeat “Display Hello”"],
    predictionRight: "Yes. The processor moves on to fetch the next instruction.",
    predictionTry: "Make a prediction, then follow the processor's steps.",
    eventLabel: "Computer event",
    initialEvent: "Now follow the full sequence from the beginning. Your prediction will not run the computer.",
    nextEvent: "Show next computer step",
    completed: "Both instructions are complete",
    reset: "Start again",
    events: [
      "The processor fetches “Display Hello”.",
      "The processor decodes “Display Hello”.",
      "The processor executes “Display Hello”.",
      "The processor fetches “Display Goodbye”.",
      "The processor decodes “Display Goodbye”.",
      "The processor executes “Display Goodbye”.",
    ],
    clockHeading: "A closer look at timing",
    clockCycleLabel: "One clock cycle",
    clockMeaning: "The system clock sends regular timing signals. In our simple step-by-step model, one clock cycle coordinates one very small processor action.",
    clockExample: "For example, the processor puts an address onto the address bus, as in the previous exploration.",
    clockDistinction: "An instruction cycle is the complete process of handling one instruction: fetching it, decoding it and carrying it out. In our step-by-step model, we can zoom in and see several small actions, each coordinated with a clock cycle; together they complete the instruction.",
    clockImageLabel: "A visual showing one clock cycle as a regular timing beat",
    home: "All explorations",
  },
  zh: {
    title: "指令周期",
    intro: "处理器会依次处理程序中的指令。",
    homeEyebrow: "你的第五次探索",
    homeIntro: "处理器怎样处理一条指令？完成之后又会怎样？",
    explore: "探索指令周期",
    instructionMeaning: "指令是一条告诉处理器要做什么的命令。",
    exampleLabel: "两条示例指令",
    instructions: ["显示“Hello”", "显示“Goodbye”"],
    cycleLabel: "不断重复的指令周期",
    cycleMeaning: "这三个阶段合起来称为指令周期。",
    phases: ["取指 Fetch", "解码 Decode", "执行 Execute"],
    phaseDescriptions: [
      "从内存中取出下一条指令。",
      "弄清楚这条指令的意思。",
      "执行这条指令。",
    ],
    loopLabel: "然后返回取出下一条指令",
    tryLabel: "试一试",
    question: "处理器执行完“显示 Hello”之后，接下来会怎样？",
    choices: ["取出下一条指令", "再次执行“显示 Hello”"],
    predictionRight: "是的。处理器接下来会取出下一条指令。",
    predictionTry: "先做出预测，再按顺序观察处理器的步骤。",
    eventLabel: "计算机事件",
    initialEvent: "现在从头观察完整过程。你的预测不会让计算机执行。",
    nextEvent: "显示计算机下一步",
    completed: "两条指令都已完成",
    reset: "重新开始",
    events: [
      "处理器正在取出“显示 Hello”这条指令。",
      "处理器正在解码“显示 Hello”这条指令。",
      "处理器正在执行“显示 Hello”这条指令。",
      "处理器正在取出“显示 Goodbye”这条指令。",
      "处理器正在解码“显示 Goodbye”这条指令。",
      "处理器正在执行“显示 Goodbye”这条指令。",
    ],
    clockHeading: "再看看计时",
    clockCycleLabel: "一个时钟周期",
    clockMeaning: "系统时钟发出规律的计时信号。在这里的简化逐步模型中，一个时钟周期协调处理器完成一个很小的动作。",
    clockExample: "例如，处理器把一个地址放到地址总线上，就像上一节看到的那样。",
    clockDistinction: "指令周期就是处理一条指令的完整过程：取出指令、弄清意思、执行指令。在这里的逐步模型中，我们可以放大观察它的好几个小动作；每个小动作由一个时钟周期协调，这些动作合起来完成整条指令。",
    clockImageLabel: "用规律计时节拍表示一个时钟周期的示意图",
    home: "全部探索",
  },
} satisfies Record<Language, Record<string, string | string[]>>;

export type InstructionCycleLanguage = Language;
